============================= test session starts ==============================
platform darwin -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/johnmount/Documents/work/wvu/pkg
plugins: anyio-3.5.0, cov-3.0.0
collected 0 items / 13 errors

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_cross_plan1.py __________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_cross_plan1.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cross_plan1.py:1: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
_________________ ERROR collecting tests/test_cross_predict.py _________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_cross_predict.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cross_predict.py:4: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
_________________ ERROR collecting tests/test_deviance_calc.py _________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_deviance_calc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_deviance_calc.py:2: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
________________ ERROR collecting tests/test_eval_fn_pre_row.py ________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_eval_fn_pre_row.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_eval_fn_pre_row.py:2: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
___________________ ERROR collecting tests/test_match_auc.py ___________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_match_auc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_match_auc.py:1: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
____________________ ERROR collecting tests/test_onehot.py _____________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_onehot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_onehot.py:3: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
________________ ERROR collecting tests/test_perm_score_vars.py ________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_perm_score_vars.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_perm_score_vars.py:4: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
_____________________ ERROR collecting tests/test_plots.py _____________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_plots.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_plots.py:5: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
______________________ ERROR collecting tests/test_se.py _______________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_se.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_se.py:5: in <module>
    from wvpy.util import suppress_stdout_stderr
E   ModuleNotFoundError: No module named 'wvpy.util'
__________________ ERROR collecting tests/test_search_grid.py __________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_search_grid.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_search_grid.py:3: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
____________________ ERROR collecting tests/test_stats1.py _____________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_stats1.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_stats1.py:2: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
________________ ERROR collecting tests/test_threshold_stats.py ________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_threshold_stats.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_threshold_stats.py:3: in <module>
    import wvpy.util
E   ModuleNotFoundError: No module named 'wvpy.util'
________________ ERROR collecting tests/test_types_in_frame.py _________________
ImportError while importing test module '/Users/johnmount/Documents/work/wvu/pkg/tests/test_types_in_frame.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../opt/anaconda3/envs/wvu_dev_env/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_types_in_frame.py:3: in <module>
    from wvpy.util import types_in_frame
E   ModuleNotFoundError: No module named 'wvpy.util'

---------- coverage: platform darwin, python 3.9.12-final-0 ----------
Name              Stmts   Miss  Cover
-------------------------------------
wvu/__init__.py       3      3     0%
wvu/util.py         321    321     0%
-------------------------------------
TOTAL               324    324     0%

=========================== short test summary info ============================
ERROR tests/test_cross_plan1.py
ERROR tests/test_cross_predict.py
ERROR tests/test_deviance_calc.py
ERROR tests/test_eval_fn_pre_row.py
ERROR tests/test_match_auc.py
ERROR tests/test_onehot.py
ERROR tests/test_perm_score_vars.py
ERROR tests/test_plots.py
ERROR tests/test_se.py
ERROR tests/test_search_grid.py
ERROR tests/test_stats1.py
ERROR tests/test_threshold_stats.py
ERROR tests/test_types_in_frame.py
!!!!!!!!!!!!!!!!!!! Interrupted: 13 errors during collection !!!!!!!!!!!!!!!!!!!
============================= 13 errors in 13.43s ==============================
